# Generated by Django 4.1 on 2022-09-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_change', models.DateField(blank=True)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg_log.category')),
            ],
        ),
    ]
