# Generated by Django 4.1 on 2022-09-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_alter_article_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_log.category'),
        ),
    ]
