# Generated by Django 4.1 on 2022-09-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0004_alter_article_id_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
