# Generated by Django 4.1 on 2022-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0005_alter_article_options_remove_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
    ]
