# Generated by Django 4.1 on 2022-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0010_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=3, upload_to='img/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
