# Generated by Django 4.1 on 2022-10-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0014_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reg_log.category'),
        ),
    ]
