# Generated by Django 4.1.2 on 2022-10-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0016_alter_article_id_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id_cat',
            new_name='cat_name',
        ),
    ]
